### ISSUE TITLE
Posts & Events Not Appearing

### ISSUE THREAD

**Issue by bekkblando** [bekkblando/art_plugin#22]
This problem is due to a conflict between the Fusion Theme v3.8.4 and Wordpress 4.6.

https://theme-fusion.com/forums/topic/wordpress-4-4-blog-shortcode-fix/

This problem is best solved by updating the fusion theme to 3.9.

However, this could have unintended styling effects and may require the reformatting of some pages(as fusion will be updated).  

Please give the go ahead for the fix, but be aware of the potential styling affects.

**Comment by macartscouncil** [comment]
Confirmed

**Comment by bekkblando** [comment]
Update was successful.

The post and event issue seems resolved.
Please Confirm.

Be on the lookout for side effects.

**Comment by macartscouncil** [comment]
Confirmed!

**Comment by bekkblando** [comment]
Great, what other bugs need to be fixed before migration?

**Comment by macartscouncil** [comment]
That’s the only bug I know of. Go ahead and start tackling the rest of the GitHub list. I think those were all directory issues, and then let me know where we are? Since we are so close to Open Studios (people will be coming to the site to use the directory) I’d like for most/all of those to be fixed if we do migrate before the event now. 

Thanks!

**Comment by bekkblando** [comment]
Ok, I will act in the priority list we set.

**Comment by macartscouncil** [comment]
That sounds good. Do you want to just let me know where you are on Sunday and then we can decide?
